### ISSUE TITLE
NoiseTorch unconditionally shows "active" when both "filter mic" and "filter headphones" are disabled.

### ISSUE THREAD

**Issue by lawl** [noisetorch/NoiseTorch#158]
If nothing is selected to be filtered, we check that indeed no filter is loaded, and since that is true, we show "NoiseTorch loaded", which may confuse users.

**Comment by Oman395** [comment]
i mean, it's not wrong

**Comment by ZyanKLee** [comment]
Perhaps the wording could be changed to something like: 'No filter selected' with a neutral color like light blue or gray.
That way the reason for the actual status is more apparent and the text is not misleading, either.

**Comment by TheDukeofErl** [comment]
I just put a PR in for this, I noticed it while I was working on different ui changes and it confused me as well, ha. 

> Perhaps the wording could be changed to something like: 'No filter selected' with a neutral color like light blue or gray.

I opted for "NoiseTorch unconfigured" to be consistent with the other messages.

**Comment by melo0187** [comment]
Don't know much go, so I'm going out on a limb here... but is [ctx.virtualDeviceInUse](url) actually evey initialized?
Just wondering, because I'm experiencing the same issue as reported in #340
