### ISSUE TITLE
Sudden Robotic Voice

### ISSUE THREAD

**Issue by daniel-evans007** [noisetorch/NoiseTorch#182]
I've been using Noise Torch for about a week, and I've noticed it's tendency to suddenly give me a robotic voice in the middle of a session, be it normal audio recording using pulse audio, or audio capture in obs. Then, all of a sudden, as if nothing was wrong, it fixes itself.

**Comment by lawl** [comment]
Is it possible that the CPU core pulseaudio is running on is maxed out during that time? Sounds to me like the denoiser can't keep up fast enough.

**Comment by daniel-evans007** [comment]
> Same thing happening here, regular input sounds fine in gnome recoder, noisetorch input sounds kinda robotic with some hiss to it.

I've found another way, google pulse audio echo cancellation, it works well enough, it's an inbuilt feature of pulseaudio. Noise cancellation isn't as strong, but blocks out my fan noise, and most importantly doesn't degrade my audio.

**Comment by lawl** [comment]
ok, in that case i'll close this issue, because there's unfortunately no actionable information here.

**Comment by Foxite** [comment]
If it's any help, I encountered this problem today, and this showed up in journalctl:

```
Dec 18 22:13:02 PcArch pulseaudio[1150]: Source minimum latency increased to 4.00 ms
Dec 18 22:13:02 PcArch pulseaudio[1150]: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
Dec 18 22:34:14 PcArch pulseaudio[1150]: Source minimum latency increased to 8.00 ms
Dec 18 22:34:14 PcArch pulseaudio[1150]: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
Dec 18 22:34:14 PcArch pulseaudio[1150]: Source minimum latency increased to 16.00 ms
Dec 18 22:34:14 PcArch pulseaudio[1150]: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
Dec 18 22:34:17 PcArch pulseaudio[1150]: Too many underruns, increasing latency to 22.00 ms
Dec 18 22:34:27 PcArch pulseaudio[1150]: Too many underruns, increasing latency to 27.00 ms
Dec 18 22:34:37 PcArch pulseaudio[1150]: Too many underruns, increasing latency to 32.00 ms
Dec 18 22:34:47 PcArch pulseaudio[1150]: Too many underruns, increasing latency to 37.00 ms
Dec 18 22:34:54 PcArch pulseaudio[1150]: Got POLLNVAL from ALSA
Dec 18 22:34:54 PcArch kernel: usb 1-1: USB disconnect, device number 2
```

(Unrelated messages removed.)

The last message (and possibly the one before that) is me actually disconnecting the microphone because that's how I usually fix the problem (disable noisetorch, reconnect microphone, enable noisetorch - only this time I accidentally disconnected the microphone before disabling noisetorch). I had been in a discord call but I was mostly quiet until shortly before I disconnected my microphone because people told me my microphone was glitching out. So it's possible that the problem would have been apparent much sooner.

Unfortunately that's all there is. There are no other audio-related messages.

**Comment by lawl** [comment]
@Foxite we'd need to know why the buffer underruns. You could try starting pulseaudio with `-vvvv` from a terminal and try to catch this occurring.

**Comment by Foxite** [comment]
I have caught the bug in action while running pulseaudio with -vvvv:

First, when the bug is not active, you just see a this every couple of seconds:
```
D: [pulseaudio] module-loopback.c: Loopback overall latency is 0.40 ms + 11.86 ms + 0.61 ms = 12.86 ms
D: [pulseaudio] module-loopback.c: Loopback latency at base rate is 12.85 ms
D: [pulseaudio] module-loopback.c: [nui_mic_raw_in] Updated sampling rate to 44082 Hz.
```
Not sure if it's relevant, but I thought I'd mention it.

When it happens, this gets logged at an absolute blazing speed:
```
D: [null-sink] sink-input.c: Have to rewind 108 bytes on render memblockq.
D: [null-sink] sink-input.c: Have to rewind 216 bytes on implementor.
D: [null-sink] module-ladspa-sink.c: Resetting plugin
D: [null-sink] sink.c: Processing rewind...
D: [null-sink] sink-input.c: Have to rewind 216 bytes on render memblockq.
D: [null-sink] source.c: Processing rewind...
D: [null-sink] source.c: Processing rewind...
D: [null-sink] source-output.c: Have to rewind 108 bytes on implementor.
D: [null-sink] source.c: Processing rewind...
D: [null-sink] module-null-sink.c: Rewound 108 bytes.
I: [null-sink] module-loopback.c: Could not peek into queue
D: [null-sink] module-loopback.c: Requesting rewind due to end of underrun.
D: [null-sink] module-null-sink.c: Requested to rewind 120 bytes.
D: [null-sink] sink.c: Processing rewind...
D: [null-sink] sink-input.c: Have to rewind 116 bytes on render memblockq.
D: [null-sink] sink-input.c: Have to rewind 232 bytes on implementor.
D: [pulseaudio] module-loopback.c: Underrun detected, counter incremented to 570
D: [null-sink] module-ladspa-sink.c: Resetting plugin
D: [null-sink] sink.c: Processing rewind...
D: [null-sink] sink-input.c: Have to rewind 232 bytes on render memblockq.
D: [null-sink] source.c: Processing rewind...
D: [null-sink] source.c: Processing rewind...
D: [null-sink] source-output.c: Have to rewind 116 bytes on implementor.
D: [null-sink] source.c: Processing rewind...
D: [null-sink] module-null-sink.c: Rewound 116 bytes.
I: [null-sink] module-loopback.c: Could not peek into queue
D: [null-sink] module-loopback.c: Requesting rewind due to end of underrun.
D: [null-sink] module-null-sink.c: Requested to rewind 116 bytes.
D: [null-sink] sink.c: Processing rewind...
D: [null-sink] sink-input.c: Have to rewind 116 bytes on render memblockq.
D: [null-sink] sink-input.c: Have to rewind 232 bytes on implementor.
D: [null-sink] module-ladspa-sink.c: Resetting plugin
D: [pulseaudio] module-loopback.c: Underrun detected, counter incremented to 571
```

This kept going until I stopped pulseaudio.

The lack of timestamps makes it a bit difficult to pinpoint when exactly this happened, there may be more valuable log data before this barrage of messages. I have saved the log file for the entire session and I can send it if you want.

The journald messages I showed before did NOT appear.

**Comment by lawl** [comment]
There's an explanation on rewinding here: https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Rewinding/

Do you remember doing anything that would cause a rewind (such as changing volume on the mic)?

**Comment by Foxite** [comment]
No, I'm pretty sure I was just in a discord call.

**Comment by lawl** [comment]
It might be best to file an issue with your distro or upstream PA. This looks like pulse is doing something weird here and i'm out of my depth. Maybe it tries to rewind but then causes the buffer to underrun and somehow gets stuck there?

One possible work around might be to increase the latency on our side to (hopefully) avoid the underruns, but that would come at an increased cost of latency for everyone else, so i'd like to avoid it.
