### ISSUE TITLE
No sound at all on NoiseTorch microphone

### ISSUE THREAD

**Issue by Aschen** [noisetorch/NoiseTorch#208]
It's very weird because Noise Torch was working when I first tried it and since then I cannot make it work again.

The virtual NoiseTorch microphone is completely silent despite that my original microphone is working great.

What kind of information can I provide to help debugging this?

<details><summary>screenshot</summary>
![image](https://user-images.githubusercontent.com/4447392/146008113-d3ed8152-ad90-4fde-912a-acb6923b790c.png)
</details>

**Comment by lawl** [comment]
Have you tried the steps outlined here: https://github.com/lawl/NoiseTorch/wiki/Troubleshooting#virtual-microphone-is-silent

?
