### ISSUE TITLE
Noisetorch seems to crash pulseaudio

### ISSUE THREAD

**Issue by Foexle11** [noisetorch/NoiseTorch#252]
Hi Folks,
since a couple of days I've got massive Problems with the newest Noisetorch version (0.11.5). It starts normally on startup, but when I try to use it for like more than 5 Minutes, Noisetorch gets inconsistent and the sources and sinks are not visible anymore. In Mint itself, none is visible, in Noisetorch only the devices I was using disappear. Restarting pulsewire with `pulsewire -k` seems to have no reaction whatsoever.
I've rolled back to the 0.11.4 and it seems to work fine.
I don't have like any idea what can cause this, so every "dumb" he, look up this and that, is appreciated.
Running Linux Mint Cinnamon 20.3 on Kernel 5.13.0-41-generic.

**Comment by lawl** [comment]
> Restarting pulsewire with pulsewire -k seems to have no reaction whatsoever.

what's pulsewire? i only know of `pipewire-pulse` or `pulseaudio`.

Also, logs of `"pulsewire"` and noisetorch?

**Comment by Foexle11** [comment]
Okay, I'm not 100% sure, cause, like everyone here, I de-installed Noisetorch, just to be 100% sure. But I've catched my microphone itself bugging, and it seems like it somehow switches from mono to a stereo driver, resulting in an autotune-like experience while my voice gets piched higher and higher. If I would have to guess, thats part of the reason everything crashed. 
I'll close this one for now, If I get to fix this driver-thing, noisetorch is back from its winter-slummer and the issue is still there, I'll reopen.
