### ISSUE TITLE
Do I have a virus now? :eyes:

### ISSUE THREAD

**Issue by DieracDelta** [noisetorch/NoiseTorch#256]
I've been running noise torch from source off nixpkgs: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/noisetorch/default.nix. Has the source itself been compromised? Or just whichever compiled binaries?

**Comment by lawl** [comment]
Nobody knows, and absence of evidence isn't evidence of absence. You'll need to use your own risk judgement for now, sorry.
