### ISSUE TITLE
updates 0.11.6

### ISSUE THREAD

**Issue by BELLECalain** [noisetorch/NoiseTorch#260]
is this only  the  0.11.6 git sources which are compromised ?
or also the zip and the tar.gz file(s)  ?
thanks

**Comment by ZyanKLee** [comment]
TL;DR: the breach has apparently been somewhen last year. so there are older versions that might have been compromised.

Full story:
* https://github.com/lawl/NoiseTorch/issues/253
* https://github.com/lawl/NoiseTorch/issues/254

**Comment by Zardoz89** [comment]
The readme, it's missing how delete it : 

## Uninstall

```
rm ~/.local/bin/noisetorch
rm ~/.local/share/applications/noisetorch.desktop
rm ~/.local/share/icons/hicolor/256x256/apps/noisetorch.png
```
