### ISSUE TITLE
Update mechanism via github releases

### ISSUE THREAD

**Issue by ZyanKLee** [noisetorch/NoiseTorch#271]
Current state: Makefile currently sets `noisetorch.epicgamer.org` as update url. 

Target state:
* binaries published to GitHub releases are being used for updates.
* make sure we provide a toggle switch of some kind to disable the update notification [:link:](https://github.com/noisetorch/NoiseTorch/issues/271#issuecomment-1137151145)

Depends on #272

**Comment by ZyanKLee** [comment]
When PR #272 is being merged, this issue has to be tackled next to get the update mechanism working again. Is there anybody that feels compelled to do this?

**Comment by principis** [comment]
For the person who will be working on this, make sure that the update mechanism can be disabled easily. This makes it much easier for package maintainers.

**Comment by ZyanKLee** [comment]
hey @principis, that is a great idea.

Currently it is relatively easy to disable the mechanism by removing the UPDATE_URL in line 1 of the Makefile. Doing that disables the update function in newly built packages. Would that be sufficient for what you need?
