### ISSUE TITLE
Bugged microphone

### ISSUE THREAD

**Issue by Jolonte** [noisetorch/NoiseTorch#273]
Hello everyone, well, I'm a little lost about what happened, but my microphone started getting buggy (understand buggy as, popped and inaudible).

I was using noise torch normally but I decided to enter its repository, which contained some instructions to uninstall it, so I did. 

I don't know if these 2 facts correlate, but I would like to know why uninstall this program that until recently was normal. If you can explain to me what really happened, thank you!

Another thing, I'm using Pop OS 22.04, it's my first Linux distribution, however when I was going to update the program, in a proper option, a "modal" appeared saying that my section didn't start correctly and also asked for my password, well I don't know if this is normal, even because it's my first distribution but when I clicked on update, it said that the update failed.

**Comment by CheaterTim** [comment]
@Jolonte 
> If you can explain to me what really happened, thank you!

from what I could gather from all the conversations like in #254, some server of lawl, the creator of NoiseTorch has been compromised. and there may be things the attacker hid in NoiseTorch, which is why removing NoiseTorch is recommended for now. so far nothing malicious has been found tho and NoiseTorch is *probably* fine

**Comment by Jolonte** [comment]
> @Jolonte
> 
> > If you can explain to me what really happened, thank you!
> 
> from what I could gather from all the conversations like in #254, some server of lawl, the creator of NoiseTorch has been compromised. and there may be things the attacker hid in NoiseTorch, which is why removing NoiseTorch is recommended for now. so far nothing malicious has been found in NoiseTorch tho and NoiseTorch is _probably_ fine

Ok, thank you very much for the feedback, well, I hope everything can be solved and nothing bad happens.

I don't know if it was an isolated case (of the mic), at least nobody else reported an issue about it, but it is still buggy, in that case do I need to reinstall the drivers?

**Comment by riderius** [comment]
I had such a problem. I fixed it by restarting pulseaudio.

**Comment by Jolonte** [comment]
> I had same a problem. I fixed it by restarting pulseaudio.

Okay, how could I do that?

**Comment by TheDukeofErl** [comment]
> > I had same a problem. I fixed it by restarting pulseaudio.
> 
> Okay, how could I do that?

Pulseaudio can be restarted by running ```systemctl --user restart pulseaudio.service```.

**Comment by Jolonte** [comment]
> > > I had same a problem. I fixed it by restarting pulseaudio.
> > 
> > 
> > Okay, how could I do that?
> 
> Pulseaudio can be restarted by running `systemctl --user restart pulseaudio.service`.

`Failed to restart pulseaudio.service: Unit pulseaudio.service not found.`
I got this error, maybe it's because I'm on Ubuntu/Pop Os?

So I tried another way, with the following command: 
`systemctl --user enable pulseaudio`

This returned the following error:
`Failed to enable unit: Unit file pulseaudio.service does not exist.`

and after:
`pulseaudio: no processes found`

So I decided to install pulseaudio via terminal, which again gave me an error :(

`sudo apt install pulseaudio`
```
Some packages could not be installed. This may mean that
you requested an impossible situation or, if you are using the
unstable distribution, that some required packages have not been
created yet or were removed from the "Incoming" distribution.
The following information may help to resolve the situation:

The following packages have mismatched dependencies:
 pop-desktop : Conflicts: pulseaudio
               Recommends: io.elementary.sideload but it is not installable
               Recommends: libreoffice-calc but it will not be installed
               Recommends: libreoffice-impress but it won't be installed
               Recommends: com.github.donadigo.eddy but will not be installed
               Recommends: libreoffice-ogltrans
               Conflicts: pulseaudio:i386
```

**Comment by Jolonte** [comment]
> > > > I had same a problem. I fixed it by restarting pulseaudio.
> > > 
> > > 
> > > Okay, how could I do that?
> > 
> > 
> > Pulseaudio can be restarted by running `systemctl --user restart pulseaudio.service`.
> 
> `Failed to restart pulseaudio.service: Unit pulseaudio.service not found.` I got this error, maybe it's because I'm on Ubuntu/Pop Os?
> 
> So I tried another way, with the following command: `systemctl --user enable pulseaudio`
> 
> This returned the following error: `Failed to enable unit: Unit file pulseaudio.service does not exist.`
> 
> and after: `pulseaudio: no processes found`
> 
> So I decided to install pulseaudio via terminal, which again gave me an error :(
> 
> `sudo apt install pulseaudio`
> 
> ```
> Some packages could not be installed. This may mean that
> you requested an impossible situation or, if you are using the
> unstable distribution, that some required packages have not been
> created yet or were removed from the "Incoming" distribution.
> The following information may help to resolve the situation:
> 
> The following packages have mismatched dependencies:
>  pop-desktop : Conflicts: pulseaudio
>                Recommends: io.elementary.sideload but it is not installable
>                Recommends: libreoffice-calc but it will not be installed
>                Recommends: libreoffice-impress but it won't be installed
>                Recommends: com.github.donadigo.eddy but will not be installed
>                Recommends: libreoffice-ogltrans
>                Conflicts: pulseaudio:i386
> ```

Oh right, with some research I found out that Pop OS does not use pulse audio, but rather Pipewires Pulse 🤡.

To reset it just use the following commands:
`nautilus $HOME/.local/state/wireplumber/`

or for some other distributions:
`nautilus $HOME/.local/state/pipewire/media-session.d/`

Then just delete this folder and reboot.
I'll see if it works now.

**Comment by TheDukeofErl** [comment]
> Oh right, with some research I found out that Pop OS does not use pulse audio, but rather Pipewires Pulse clown_face.

Makes sense, I wasn't sure if PopOS went with Pipewire for 22.04 or not. For what it's worth, restarting Pipewire can be done as follows: ```systemctl --user restart pipewire pipewire-pulse pipewire-media-session```. One thing worth noting too is that you might be using ```wireplumber``` instead of ```pipewire-media-session```. I know Arch defaults to wireplumber now but I'm not sure what PopOS does.

> Then just delete this folder and reboot.

I believe that logging in and out should be good enough as well, given that pipewire *should* be a user service, but rebooting won't hurt :)

**Comment by Jolonte** [comment]
It really worked!!! I'm even more relieved :D

Well, I would like to thank everyone here for their support anyway. I hope others have been helped with this as well. My sincere thanks, I will be closing this issue.

About NoiseTorch, I hope it will be back to normal soon, I'll be looking for an alternative to it until things get back to normal.
