### ISSUE TITLE
Possible compromise, read here

### ISSUE THREAD

**Issue by MissLav** [noisetorch/NoiseTorch#274]
![Screenshot_20220521_023017](https://user-images.githubusercontent.com/51702517/169641072-29a0c3f9-e652-4361-b2b6-eaddcd2efe70.png)
sorry for poor formatting

**Comment by bogdancovaciu** [comment]
Have your read this ?
https://github.com/noisetorch/NoiseTorch/releases/tag/0.11.6

**Comment by MissLav** [comment]
ah thanks should i uninstall from aur and then install from the latest github build?

**Comment by MissLav** [comment]
im using the bin from the aur currently

**Comment by bogdancovaciu** [comment]
I recommend you to remove it ASAP and eventually use the `noisetorch` from AUR instead, so it builds from source and not the compromised binary.

**Comment by ZyanKLee** [comment]
For now I would recommend to NOT use NoiseTorch at all. We are currently in the process of auditing the whole code and making sure it has not been tampered with (#264 and #275).
Until that is finished, we can not be sure neither the code base nor the binaries are secure.

**Comment by bogdancovaciu** [comment]
Really sorry to hear about the breach into your code and thanks for making us aware!
