### ISSUE TITLE
undeclared name: `licenseString` (typecheck)

### ISSUE THREAD

**Issue by ZyanKLee** [noisetorch/NoiseTorch#277]
Check out what's wrong here and fix the issue reported by `golangci-lint`:

finding: https://github.com/noisetorch/NoiseTorch/runs/6535494424?check_suite_focus=true#step:5:22

relevant code: https://github.com/noisetorch/NoiseTorch/blob/2d96609a6cfeb8fbc6dbccbeb4e17ec527f1c366/ui.go#L382

**Comment by Dadadah** [comment]
This variable is generated by the scripts/embedlicenses script. `go generate` runs that script and writes a new file that contains that variable in it.

**Comment by ZyanKLee** [comment]
So, we'll figure that one, too. Thanks!
