### ISSUE TITLE
 `main` redeclared in this block (typecheck)

### ISSUE THREAD

**Issue by ZyanKLee** [noisetorch/NoiseTorch#278]
checkout what is wrong here and fix the issue reported by `golangci-lint`:

finding: https://github.com/noisetorch/NoiseTorch/runs/6535494424?check_suite_focus=true#step:5:23

related code: 

https://github.com/noisetorch/NoiseTorch/blob/2d96609a6cfeb8fbc6dbccbeb4e17ec527f1c366/scripts/embedlicenses.go#L10

https://github.com/noisetorch/NoiseTorch/blob/2d96609a6cfeb8fbc6dbccbeb4e17ec527f1c366/scripts/signer.go#L15

**Comment by Dadadah** [comment]
I don't think this is an issue. Both of these files are ran as individual scripts in the Makefile using `go script` which requires a main method for each script. We can either ignore this error or move each script into it's own package.

**Comment by ZyanKLee** [comment]
If ignoring works, I'm fine with that. Thanks for the feedback
