### ISSUE TITLE
Create noisetorch org fork of lawl/pulseaudio

### ISSUE THREAD

**Issue by TheDukeofErl** [noisetorch/NoiseTorch#298]
Prior to the release of a new version, I believe https://github.com/lawl/pulseaudio should be forked into the organization and go.mod/go.sum should be changed to point to that fork instead. The pulseaudio vendor code is something that's essentially just used by NoiseTorch and will likely need to be maintained by us going forward.

If there are updates to upstream, we can pull them in accordingly, much like noisetorch/rnnoise and noisetorch/c-ringbuf.

**Comment by ZyanKLee** [comment]
Reopened: missed the second part of changing the references in the code.

Point is: go mod does not want to use `github.com/noisetorch/pulseaudio` as the module anounces itself as `github.com/lawl/pulseaudio`

So, either we change `github.com/noisetorch/pulseaudio` to announce itself "correctly", or we continue using lawl's repo but keep our fork for safekeeping.

**Comment by TheDukeofErl** [comment]
I'll plan on looking at getting noisetorch/pulseaudio to announce itself properly so that we can use that instead. For the v0.12.0 release we can probably look at that as a stretch goal: if it's not ready in time for v0.12.0, it's not a huge issue in my opinion. More than anything, like you said, it's for safekeeping.

**Comment by Technetium1** [comment]
> I'll plan on looking at getting noisetorch/pulseaudio to announce itself properly

https://github.com/noisetorch/pulseaudio/blob/ed754c0c6618ee6320b27be07b73231fb98802ff/go.mod#L1

**Comment by TheDukeofErl** [comment]
> https://github.com/noisetorch/pulseaudio/blob/ed754c0c6618ee6320b27be07b73231fb98802ff/go.mod#L1

Yeah, I imagine it's more or less just changing that and changing the go.mod and go.sum in this repo accordingly.

**Comment by TheDukeofErl** [comment]
Created https://github.com/noisetorch/pulseaudio/pull/1 to progress this along. I don't really think anything else is really needed for that repo. If there is it'll be easier to spot once the module name is updated :)

**Comment by TheDukeofErl** [comment]
Okay, this is implemented and merged, closing.
