### ISSUE TITLE
Restore and modify README.md

### ISSUE THREAD

**Issue by ZyanKLee** [noisetorch/NoiseTorch#300]
Before release v0.12.0 we still need to fixup the README to reflect the current state:

* normal project information and short user guide
* announce code is clean
* ...

**Comment by AXDOOMER** [comment]
I'm almost done reviewing the source code and diffing the binaries for any potential backdoors. When I'm done (probably this weekend), I can do a PR restoring the previous README and add information regarding what the community has do to ensure this software is safe to use.
