### ISSUE TITLE
Should this be noisetorch/NoiseToch?

### ISSUE THREAD

**Issue by RiemaruKarurosu** [noisetorch/NoiseTorch#307]
I was checking some of the code, and I'm not sure if this should be link to noisetorch/NoiseTorch or it doesn't affect.

https://github.com/noisetorch/NoiseTorch/blob/a90216813ebd34dd28cbbef2e39b2245de283027/ui.go#L14

**Comment by ZyanKLee** [comment]
That might some day become `noisetorch/pulseaudio` but for that we would need to change the go.mod file in the pulseaudio repo. As we don't expect lawl to pull down the repo anytime soon and we are having a fork already (better safe than sorry), we are not in a hurry, though.

**Comment by RiemaruKarurosu** [comment]
Ok, thanks, just asking

**Comment by TheDukeofErl** [comment]
Just to link the tickets, https://github.com/noisetorch/NoiseTorch/issues/298 is the related issue for the lawl/pulseaudio -> noisetorch/pulseaudio eventual switchover (if necessary).

**Comment by ZyanKLee** [comment]
> Ok, thanks, just asking

Nothing wrong with that 🙂
