### ISSUE TITLE
Invalid GPG .sig file in 0.12.0 release

### ISSUE THREAD

**Issue by m0wer** [noisetorch/NoiseTorch#310]
```bash
% gpg --verify NoiseTorch_x64_v0.12.0.tgz.sig
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
```

**Comment by ZyanKLee** [comment]
Hey @m0wer 

This signature can be verified by the signer.go script from the repo itself, which uses a special algorithm that is also used by noisetorch internally to verify updates after download. As that has been in use by noisetorch for some time now, we did not replace it, although it may be confusing.

Because it is not the usual checksum process, I also added the md5sum and sha512sum for simple verification.

We can think about completely replacing this custom signature with another checksum format in future releases.

Sorry for the confusion this led to.

**Comment by m0wer** [comment]
Thanks for the answer.

I would suggest to use GPG instead/additionally since it's well known and audited. As a user, trying to audit `singer.go` is not appealing and even if everything looked good it would be less reliable than good old GPG.

Thanks for the cool project!

**Comment by ZyanKLee** [comment]
I dug a little deeper.
The misunderstanding was that the signature would have been created with gpg. But it's actually an ed25519 based signature.

I found some discussion from which I deduct, that one should in theory be able to verify it with the help of openssl starting from v3.

https://github.com/openssl/openssl/issues/6988#issuecomment-618297128

**Comment by m0wer** [comment]
That's great! Thanks.

**Comment by m0wer** [comment]
If anyone is interested, the command should be something like this:

```bash
openssl pkeyutl -verify -pubin -inkey key.pem -sigfile NoiseTorch_x64_v0.12.0.tgz.sig -in NoiseTorch_x64_v0.12.0.tgz
```

With `key.pem` containing:

```
-----BEGIN PUBLIC KEY-----
Md2rdsS+b6W0trgcqa5lAWP978Zj0sFmubJ252OPKwc=
-----END PUBLIC KEY-----
```
which I got from the Makefile.

But I didn't manage to run it successfully:

```text
Could not read public key from key.pem
48BBBCA33B7F0000:error:1E08010C:DECODER routines:OSSL_DECODER_from_bio:unsupported:crypto/encode_decode/decoder_lib.c:101:No supported data to decode
```

**Comment by mtav** [comment]
For anyone wanting to use the signer.go script to verify the signature, here is how to use it (running from the repository root, with the .tgz and .tgz.sig files placed in ./bin):

`go run scripts/signer.go -k "Md2rdsS+b6W0trgcqa5lAWP978Zj0sFmubJ252OPKwc="  -f ./bin/NoiseTorch_x64_v0.12.2.tgz`

Where "Md2rdsS+b6W0trgcqa5lAWP978Zj0sFmubJ252OPKwc=" is the public key listed in the Makefile in the git repository.

I agree with m0wer that gpg signing would be better. And the public key should be on a separate website just in case the repository gets compromised.

I also could not get m0wer's openssl command to work to check the signature.

**Comment by mtav** [comment]
How to verify the signature using OpenSSL for those interested:
```
##### Define public ED25519 key in base64 encoded format (obtained from the Makefile):
UPDATE_PUBKEY="Md2rdsS+b6W0trgcqa5lAWP978Zj0sFmubJ252OPKwc="

##### Decode public key into a 32 byte binary file:
echo "${UPDATE_PUBKEY}" | base64 --decode > pubkey.noisetorch.bin

##### Create public ED25519 key in OpenSSL DER format:
header="30 2A 30 05 06 03 2B 65 70 03 21 00" # Necessary header for the OpenSSL DER format
hex=$(xxd -plain -cols 32 pubkey.noisetorch.bin)
echo "${header}${hex}" | xxd -revert -plain > pubkey.noisetorch.der

##### Convert DER to PEM format:
openssl pkey -pubin -inform der -in pubkey.noisetorch.der -pubout -out pubkey.noisetorch.pem

##### Optional: Print out keys in hex format for checking:
openssl pkey -pubin -inform der -in pubkey.noisetorch.der -noout -text
openssl pkey -pubin -inform pem -in pubkey.noisetorch.pem -noout -text

##### Verify signature using DER or PEM format:
openssl pkeyutl -verify -pubin -inkey pubkey.noisetorch.der -sigfile NoiseTorch_x64_v0.12.2.tgz.sig -rawin -in NoiseTorch_x64_v0.12.2.tgz
openssl pkeyutl -verify -pubin -inkey pubkey.noisetorch.pem -sigfile NoiseTorch_x64_v0.12.2.tgz.sig -rawin -in NoiseTorch_x64_v0.12.2.tgz
```

System infos:
```
$ xxd --version
xxd 2022-01-14 by Juergen Weigert et al.
$ openssl version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.04
Release:        23.04
Codename:       lunar
```

It would be very useful to document how to verify the signature in the main README, at least using the `signer.go` script.
