### ISSUE TITLE
The Application Volume Names Are Not Displayed

### ISSUE THREAD

**Issue by Codiecher** [noisetorch/NoiseTorch#312]
I understand this may not be up there as a priority, but I just wanted to point out this bug.

In the Ubuntu Sound Settings, the two outputs created by Noisetorch have no names.
[Ref 1]
![image](https://user-images.githubusercontent.com/49608838/171780337-df9eba5c-a00f-4eea-8ece-8acfde261c49.png)

But when [Application Volume Mixer](https://github.com/mymindstorm/gnome-volume-mixer) shows these two outputs, they have names.
[Ref 2]
![image](https://user-images.githubusercontent.com/49608838/171780456-f76ebf2d-c629-45ed-898d-c4acc20f2358.png)
As you can see, when Noisetorch is activated, it creates two outputs that only serve to clutter up the UI for the user. When this is used with [Application Volume Mixer](https://github.com/mymindstorm/gnome-volume-mixer) from Gnome Extensions, it takes up space in the extension box (refer to Ref 2). 

Now the extension has the function to hide certain outputs.
[Ref 3]
![image](https://user-images.githubusercontent.com/49608838/171781144-13fdfa74-0b6d-4227-aed2-8dafcf8470b9.png)

But when I input 'LADSPA Stream' as a key it did not hide it, so I figured it might link back to the problem where the outputs have no names in the Ubuntu Sound Settings (refer to Ref 1). It can't be the problem with the extension as it successfully hid 'mpv' as an output.

System Settings:
OS: Ubuntu 20.04.4 LTS
KERNEL: 5.13.0-41-generic
GNOME Version: 3.36.8

**Comment by TheDukeofErl** [comment]
> the two outputs created by Noisetorch have no names

What configuration do you have NoiseTorch in here? That is to say, what filters do you have loaded? I'd also be curious to see the logs, `noisetorch -log`. I'd also like to confirm that you're using the latest release, v0.12.0.

It may also be worth checking exactly what sinks there are with a tool dedicated to the task, such as `pavucontrol`. It's what I've generally gone for for looking at pulseaudio (and pipewire), as in the past I've found both GNOME and KDE's tools to not be quite up to the task. That said, I'm not at all familiar with Application Volume Mixer, which may do a better job than the inbuilt tools.

It's also worth noting that the inputs and outputs should be named something along the lines of "NoiseTorch Microphone for <SOURCE> Source" and NoiseTorch Headphones Sink, accordingly.

**Comment by ZyanKLee** [comment]
I also can't reproduce this (on ubuntu-studio 21.10 kde with pipewire 0.3.51). All the virtual interfaces are correctly named:

![grafik](https://user-images.githubusercontent.com/1178490/171796703-4a356791-5520-455d-9693-e67aa47ae838.png)

perhaps with some more information we can get to the root of the issue:

```
# get which audio server you are using:
LANG=C pactl info  | grep -E "Server (Name|Version|Protocol)"
# start noisetorch with debug logging to stdout enabled
noisetorch -log
# finally get an overview of the pa/pw status when NoiseTorch is loaded
LANG=C pactl list short

**Comment by Codiecher** [comment]
[Output of 'noisetorch -log' ](https://pastebin.com/8zDQ6KYD)

`codiecher@codie:~$ LANG=C pactl info  | grep -E "Server (Name|Version|Protocol)"`
`Server Protocol Version: 33`
`Server Name: pulseaudio`
`Server Version: 13.99.1`

[Output of 'LANG=C pactl list short after noisetorch is loaded with the config(refer to Ref 4)'](https://pastebin.com/ZJkwt7W8)

[Ref 4]
![image](https://user-images.githubusercontent.com/49608838/171799575-855d57e8-4848-4438-8b71-f7196b7f455e.png)

[Ref 5]
![image](https://user-images.githubusercontent.com/49608838/171799614-1856fab2-0e5e-44a1-abe9-4c4d6711ad73.png)

**Comment by ZyanKLee** [comment]
Awesome!

From the noisetorch log and pactl listing I would expect it to be correctly set.

Can you please check if `pavucontrol` shows the correct names? Perhaps you need to install it from the distro repos first.
For me pavucontrol looks like this: 
![grafik](https://user-images.githubusercontent.com/1178490/171807769-5e5742f3-e6a1-4ba4-bd6b-07aef1c529c0.png)

I'm suspecting an issue in the Gnome UI. (However that may have slipped their attention... ?)

**Comment by Codiecher** [comment]
![image](https://user-images.githubusercontent.com/49608838/171810477-aa53c70f-52e1-4b3f-a247-97dcded8f318.png)
![image](https://user-images.githubusercontent.com/49608838/171810504-19c6fb98-6bbe-40e3-a7be-5df385b6522a.png)
Are the two output devices supposed to be created? 
This is my Noisetorch config: 
![image](https://user-images.githubusercontent.com/49608838/171810570-46443dfe-2043-4a09-bd2f-d12cf938a9b2.png)

I tried adding 'Null Output' and the other one to the extension's filter, but they still aren't filtered as outputs.

**Comment by ZyanKLee** [comment]
>  Are the two output devices supposed to be created?

I think so, yes. They are basically the patching cables that make up the internal audio routing.

About how to filter out the outputs from the gnome-volume-mixer, I have no clue. Did you try to use the actual names from the `pactl list short` output?

**Comment by Codiecher** [comment]
> About how to filter out the outputs from the gnome-volume-mixer, I have no clue. Did you try to use the actual names from the `pactl list short` output? The ones that start with `nui_`
Yep, I have tried literally every name I've come across. Seems like it has nothing to do with noisetorch then, I'm just gonna live with it.
