### ISSUE TITLE
Update Failed!

### ISSUE THREAD

**Issue by arghanath007** [noisetorch/NoiseTorch#319]
# I see the update button but when I click it. It says Update failed!

![image](https://user-images.githubusercontent.com/54589605/171979947-3dd9b93a-6274-4465-9190-0d1532944426.png)
>After I click on the update button. It says this.

![image](https://user-images.githubusercontent.com/54589605/171980058-1dc96a97-bca4-4dc4-a035-59e89d72d15e.png)

**Comment by AXDOOMER** [comment]
Hi @arghanath007 ! 

Please download the new release from the [releases page](https://github.com/noisetorch/NoiseTorch/releases/tag/v0.12.0). We've improved the release scheme so it's more secure. The old update server is no longer used. 

I'll close this issue. Feel free to reopen if you're still experiencing problems after installer the latest release.

**Comment by arghanath007** [comment]
# Thanks for the help.
>I mistakely removed/uninstalled it before unloading it. So it is still selected as the Voice output. Will it cause any problem? I am installing the latest release as well.

**Comment by arghanath007** [comment]
Updated to the newer version. Working fine.
![image](https://user-images.githubusercontent.com/54589605/171985412-8fb167d3-24be-4d88-b384-385149509c14.png)

> I have to load it whenever I restart my PC. So is there a way to load it automatically whenever I restart my PC. Like a startup application. That would be helpful. Thanks

**Comment by AXDOOMER** [comment]
> I mistakely removed/uninstalled it before unloading it. So it is still selected as the Voice output. Will it cause any problem? I am installing the latest release as well.

I don't know. If you see any problems, restart your PC. 

> I have to load it whenever I restart my PC. So is there a way to load it automatically whenever I restart my PC. Like a startup application. That would be helpful. Thanks

I'm not familiar with this, but I think the following could help you: 

https://github.com/noisetorch/NoiseTorch/wiki/Start-automatically-with-Systemd

**Comment by arghanath007** [comment]
> I'm not familiar with this, but I think the following could help you.
>https://github.com/noisetorch/NoiseTorch/wiki/Start-automatically-with-Systemd

I mean whenever I turn back on my PC. NoiseTorch unloads and I have to load it again to use it. I have to do this everytime I turn off my system and turn it back on again. I was thinking if there is some script or some checkbox which will make it load automatically on every system start up. I don't have to worry about loading it again everyday.

**Comment by Technetium1** [comment]
The link you were just given has the answers you want @arghanath007.

**Comment by arghanath007** [comment]
Thanks for the help. It solved my issue.
