### ISSUE TITLE
Github can return api rate limit for ip.

### ISSUE THREAD

**Issue by compico** [noisetorch/NoiseTorch#321]
Github can return api rate limit for ip.

I installed  noisetorch service according to the instructions https://github.com/noisetorch/NoiseTorch/wiki/Start-automatically-with-Systemd 
By my mistake, the program restarted endlessly. As a result I got a softban in github api.

GET https://api.github.com/repos/noisetorch/NoiseTorch/releases?per_page=1&page=1
```json
{
    "message" : "API rate limit exceeded for ip XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url" : "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```
Noisetorch Error:
```
Reading JSON for latest_release failed json: cannot unmarshal object into Go value of type main.github_releases
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.getLatestRelease()
	noisetorch/update.go:199 +0x477
main.init()
	noisetorch/update.go:77 +0x2e
```

_Originally posted by @compico in https://github.com/noisetorch/NoiseTorch/issues/316#issuecomment-1146781029_

- [ ] Add in github_releases struct field `message` and `documentation_url`.
- [ ] Add reading headers http request for caching 
`x-ratelimit-limit`
`x-ratelimit-remaining`
`x-ratelimit-reset`
`x-ratelimit-used`
- [ ] Add caching body in function getLatestRelease() to limit the number of requests.

**Comment by stasadev** [comment]
I propose to change the URL from https://api.github.com/repos/noisetorch/NoiseTorch/releases?per_page=1&page=1 to https://api.github.com/repos/noisetorch/NoiseTorch/releases/latest

It will remove unneeded array here.

**Comment by Technetium1** [comment]
Welcome to steal any of the logic for my GitHub release update check here: https://github.com/Technetium1/ChocolateyUpdate/blob/40b481391d2dfe98f17e734549c1ff8a16665138/ChocolateyUpdate.py#L108

**Comment by AXDOOMER** [comment]
I've pushed an update so that being rate limited does not result in a crash. I'll will be merged when @ZyanKLee comes back.

**Comment by compico** [comment]
https://github.com/noisetorch/NoiseTorch/blob/68991f82bb82291e593847533bf1ac7c8cbf1f74/update.go#L185-L194

Here is a useless declaration of a variable `respBytes`.
Can be shortened to 
```
	body, readErr := ioutil.ReadAll(res.Body)
	if readErr != nil {
		log.Fatal(readErr)
	}

	var latest_release github_releases

	err = json.Unmarshal(body, &latest_release)
```

**Comment by AXDOOMER** [comment]
Thank you for your suggestions @compico and @stasadev. I'll do some refactoring once https://github.com/noisetorch/NoiseTorch/pull/317 is merged.

**Comment by AXDOOMER** [comment]
Crash fixed in https://github.com/noisetorch/NoiseTorch/pull/317 which has just been merged. 

As for the rate limit, Github allows 50 API requests per hour per IP, so I think it's enough. I took note of your suggestions and will apply them very soon.
