### ISSUE TITLE
Noisetorch won't start

### ISSUE THREAD

**Issue by SkyKwas** [noisetorch/NoiseTorch#327]
Hi, I'm trying to start Noisetorch, but I keep getting an error message. I've tried reinstalling it several times and the troubleshooting steps, but it still won't start.

I get a window saying:
> Noisetorch currently does not have the capabilities to function properly.
> We require CAP_SYS_RESOURCE. If that doesn't mean anything to you, don't worry. I'll fix it for you.
>
> Warning: File has CAP_SYS_RESOURCE but our process doesn't.
> Check if your filesystem has nosuid set or check the troubleshooting page.

The log file includes:
> Application starting. Version: v0.12.0 (official)
> CAP_SYS_RESOURCE: false
> Checking if config needs to be initialized
> Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/XXX/.config'
> Wrote temp librnnoise to: /tmp/librnnoise-1542910918.so
> Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/XXX/.config'
> Audioserver package name: pulseaudio
> Audioserver package version: 13.99.1
> Detected PulseAudio
> Getting caps for: /home/XXX/.local/bin/noisetorch
> Audioserver package name: pulseaudio
> Audioserver package version: 13.99.1
> Detected PulseAudio
> Connected to audio server. Server name 'PulseAudio'

I checked my filesystem to make sure nosuid was not added as a modifier using the GNOME "Disks" application.

OS: Linux Mint

**Comment by TheDukeofErl** [comment]
Would you please check the capabilities of the noisetorch binary by running `getcap ~/.local/bin/noisetorch`?

**Comment by SkyKwas** [comment]
I get
> /home/XXX/.local/bin/noisetorch = cap_sys_resource+ep

**Comment by TheDukeofErl** [comment]
Would you please post the output of `mount`?

**Comment by SkyKwas** [comment]
The output of mount? What do I type?

**Comment by ZyanKLee** [comment]
type `mount`

**Comment by SkyKwas** [comment]
> sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=32836672k,nr_inodes=8209168,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=6576680k,mode=755)
/dev/mapper/vgmint-root on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=15546)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
/dev/nvme0n1p2 on /boot type ext4 (rw,relatime)
/dev/nvme0n1p1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/mapper/luks-XXX on /media/XXX/XXX type ext4 (rw,nosuid,nodev,relatime,x-gvfs-show)
tmpfs on /run/XXX/1000 type tmpfs (rw,nosuid,nodev,relatime,size=6576676k,mode=700,uid=1000,gid=1000)
/home/.ecryptfs/XXX/.Private on /home/XXX type ecryptfs (rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=XXX,ecryptfs_sig=XXX,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)
gvfsd-fuse on /run/XXX/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
portal on /run/XXX/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)

**Comment by TheDukeofErl** [comment]
> /home/.ecryptfs/XXX/.Private on /home/XXX type ecryptfs (rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=XXX,ecryptfs_sig=XXX,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)

It looks like your homedir (/home/XXX) is mounted with the nosuid option which is causing the issue. You could check/change your fstab (/etc/fstab) to adjust this, however, I'm not familiar with encryptfs or the intricacies of using it, so that would be a "proceed at your own risk" situation. 

Alternatively, you could choose to put noisetorch in /opt and adjust the desktop files accordingly, as it appears that your root part does not have nosuid set. This is outlined in https://github.com/noisetorch/NoiseTorch/issues/106#issuecomment-799668537.

**Comment by SkyKwas** [comment]
When I installed Mint, I selected the option "use LVM with encryption". I'm guessing that's the issue.

**Comment by SkyKwas** [comment]
I actually just checked /etc/fstab and the only modifier is
> errors=remount-ro

for the boot drive (500 GB).

The only drive (6.0 TB) that has nosuid is the other one with modifiers:
> nosuid, nodev, nofail, x-gvfs-show

Here is my current drive setup, it's quite different and more complicated than a standard installation of Mint:
![pic](https://user-images.githubusercontent.com/47505256/172931518-cd874ac7-67d0-4fe7-a9f8-044cd842107b.png)


I'm sure if I make a virtual machine without LVM+encryption, it will work; but I want to keep my full-drive encryption. As for mounting it in a different location, I don't feel like manually updating Noisetorch for every new release. So I guess I'll just have to live without Noisetorch for the time being.

Are there any plans to not require the setcap for future releases?

**Comment by SkyKwas** [comment]
Okay, yeah. I just did some research and testing.

I made two similar Mint VMs with one related difference:
- Linux Mint A is installed with "encrypt home folder" selected
- Linux Mint B is installed with "encrypt home folder" NOT selected

As a side note, both had LVM+encryption.

I installed Noisetorch on both of them:
- Linux Mint A had the same problems as stated in this issue
- Linux Mint B worked

So yes, you are correct (I never doubted you)--the "encrypt home folder" option is causing the problem and that the problem is NOT caused by LVM nor it's encryption option. After doing some research, the "encrypt home folder" option uses ecryptfs (just like you said).

So I guess I'll just reinstall Mint without "encrypt home folder"; it is kind of redundant since I'm already using LVM+encryption (LUKS full-drive encryption); there's no point in having both on since I already get what I want from LUKS. From what I've learned, ecryptfs can lower performance because it encrypts/decrypts "as-needed" files, this is bad for having a bunch of small-sized files. I read that I can create another user without home folder encryption and move files over to that user, but... eeh; I like the clean install method.

With that said, I think my problem is fixed. I feel like this can be a common issue for many people (like me) who are new to Linux and see in their distribution installer, "encrypt home folder" and be like, "Yeah, who wouldn't want that?" I know Linux Mint has it, and I think Manjaro, and several other distributions, if not all, have this option. I was wondering if you wanted to add to the home page/installation instructions of this GitHub saying something like:

"NOTE: If you are using home folder encryption or some form of ecryptfs, Noisetorch may not work properly."

**Comment by TheDukeofErl** [comment]
Glad it's all figured out now :)

A lot of distro installers are kind of unclear as to what they're doing and lack the level of customization that I've wanted in the past so I feel you there. I'm hoping that as the prevalence of LUKS increases there will be fewer confusing setups that new users end up in. When considering LUKS, there probably aren't that many use cases for ecryptfs anymore anyways, other than multiuser systems.

> I was wondering if you wanted to add to the home page/installation instructions of this GitHub saying something like:
>
> "NOTE: If you are using home folder encryption or some form of ecryptfs, Noisetorch may not work properly."

This is probably a good candidate to add to the troubleshooting section. I'll update the related CAP_SYS_RESOURCE section with information on this specifically, as well as add more explicit information on figuring out if nosuid is set.

**Comment by SkyKwas** [comment]
Awesome. You may even want to add a link to this specific issue so users can get the full story.

Thank you so much for helping me with this.

I think I'm ready to close this issue now.
