### ISSUE TITLE
[Feature Request] Voice recognition?

### ISSUE THREAD

**Issue by YourSandwich** [noisetorch/NoiseTorch#329]
Hi, 
i love your Project and am wondering if it is possible to implement voice recognition into it?
This would be very impressive if I could be in a meeting at the same-time with my gf and we could talk normally.

Or for example watch youtube on speakers. 

I imagine this would be rely hard to implement and we would need some kind of AI deep learning for it but maybe there is already an simple library.

**Comment by ZyanKLee** [comment]
Hey @YourSandwich 
I'm not 100% sure I got what you are aiming to do with voice recognition.
But from my understanding, the feature you actually want is "echo cancellation" (#24) which filters from the microphone input what is being output from the speakers.
Is that right?

**Comment by YourSandwich** [comment]
@ZyanKLee Thank you, youl right echo cancellation would do 2/3 cases that i would imagine, makeing Speech recognition unworthy since to much effort to implicate.

Closing since its an duplicate of #24 in this case.
