### ISSUE TITLE
Failing to start noisetorch

### ISSUE THREAD

**Issue by kkazakov** [noisetorch/NoiseTorch#333]
When trying to start the latest ( 0.12 ) release, I get the following error:

`
➜  Downloads ~/.local/bin/noisetorch 
2022/06/14 08:08:28 Couldn't fetch latest release Get "https://api.github.com/repos/noisetorch/NoiseTorch/releases?per_page=1&page=1": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x727310]
`

About one second after the app starts. When opening the url directly, it takes about 2 seconds (always) to open it. Why would it timeout at the first second?

It does not matter which build I'm using - I built it on Manjaro, downloaded bin file - the error is the same every time.

**Comment by JucanAndreiDaniel** [comment]
Had the same issue, Manjaro also. Try to clone the repo and built it yourself. That worked for me.

**Comment by AXDOOMER** [comment]
This issue is already fixed although we haven't made a new release yet. This error may occur if you don't have an active internet connection or when Github takes too much time to respond.
