### ISSUE TITLE
"couldn't parse server version, regexp didn't match version"

### ISSUE THREAD

**Issue by lgrn** [noisetorch/NoiseTorch#339]
**Describe the bug**
Noisetorch is unable to parse the package version provided.

**To Reproduce**
1. run noisetorch with pulseaudio 16

```
$ noisetorch -i -log
2022/06/19 11:01:11 Application starting. Version: 0.12.2 (archlinux)
2022/06/19 11:01:11 CAP_SYS_RESOURCE: true
2022/06/19 11:01:11 Checking if config needs to be initialized
2022/06/19 11:01:11 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/foo/.config'
2022/06/19 11:01:11 Wrote temp librnnoise to: /tmp/librnnoise-2953609971.so
2022/06/19 11:01:11 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/foo/.config'
2022/06/19 11:01:11 Audioserver package name: pulseaudio
2022/06/19 11:01:11 Audioserver package version: 16.0
2022/06/19 11:01:11 Detected PulseAudio
2022/06/19 11:01:11 couldn't parse server version, regexp didn't match version: 16.0
2022/06/19 11:01:11 Querying pulse rlimit
2022/06/19 11:01:11 Rlimit: {Cur:200000 Max:200000}. Trying to remove.
2022/06/19 11:01:11 Rlimit: {Cur:18446744073709551615 Max:18446744073709551615}
2022/06/19 11:01:11 Loading supressor for pulse
2022/06/19 11:01:11 Loaded null sink as idx: 35
2022/06/19 11:01:11 Loaded ladspa sink as idx: 36
2022/06/19 11:01:11 Loaded loopback as idx: 37
2022/06/19 11:01:11 Loaded remap source as idx: 38
2022/06/19 11:01:11 Deleted temp librnnoise: /tmp/librnnoise-2953609971.so
```

**Expected behavior**
Presumably it should be parsed. It looks like maybe it's hardcoded to expect a version number like 1.2.3 which causes issues with versions like 16.0.

I haven't looked much at the code but if the purpose of this is to check that the pipewire version isn't too old, maybe it should be rewritten to not print anything if pipewire isn't being used.

It looks like the error is generated on this line: https://github.com/noisetorch/NoiseTorch/blob/489505ec2f60c8c778a9da5b5d1b8ba27101e2e0/main.go#L247 

```go
	res := versionRegex.FindStringSubmatch(versionString)
	if len(res) != 4 {
		log.Printf("couldn't parse server version, regexp didn't match version: %s\n", versionString)
		return audioserverinfo{servertype: servertype}, nil
	}
```

**Desktop (please complete the following information):**
 - Manjaro 21.2.6
 - Pulseaudio/Pipewire Version: `pulseaudio 16.0-1`
 - NoiseTorch Version [e.g. v0.12.0]: `noisetorch 0.12.2-1`

**Additional context**
Extra credit: `noisetorch --version` should return current version.

**Comment by TheDukeofErl** [comment]
Yup, agree. This is a good candidate for revisiting after https://github.com/noisetorch/NoiseTorch/issues/359 is completed.

**Comment by rajkumarGosavi** [comment]
Hi team,
Can I pick this up?

**Comment by AXDOOMER** [comment]
> Hi team, Can I pick this up?

Sure.

**Comment by AXDOOMER** [comment]
Fixed.
