### ISSUE TITLE
Troubleshooting didn't solve "Warning: File has CAP_SYS_RESOURCE but our process doesn't. Check if you filesystem has nosuid set or check the troubleshooting page"

### ISSUE THREAD

**Issue by MrAlves17** [noisetorch/NoiseTorch#341]
Hello, I have tried to solve the CAP_SYS_RESOURCE problem, but after clicking at the `Grant capability (requires root)` button, It appears this message:

`Warning: File has CAP_SYS_RESOURCE but our process doesn't. Check if you filesystem has nosuid set or check the troubleshooting page`

I tried to follow the troubleshooting page, but didn't solve.
The message: `Couldn't setcap self as root: exit status 127` didn't appear in the log (https://pastebin.com/mrvWrgLY).
Also, when executing `getcap ~/.local/bin/noisetorch`, this happens:

`/home/vitor/.local/bin/noisetorch = cap_sys_resource+eip`

But this is not equal to `<path> cap_sys_resource=eip`, right? 

The command `mount | grep home`, shows this:
`/home/.ecryptfs/vitor/.Private on /home/vitor type ecryptfs (rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=e10621024c1ee7b9,ecryptfs_sig=b3450cae1efd6006,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)`

What should I do? 

Thanks.

**Comment by TheDukeofErl** [comment]
Your issue is the same as the one in https://github.com/noisetorch/NoiseTorch/issues/327. Your home filesystem (/home/vitor) needs to be mounted without nosuid set. Possible workaround include installing the program in a non-standard location, such as /opt, as outlined in https://github.com/noisetorch/NoiseTorch/issues/106.

**Comment by MrAlves17** [comment]
Thanks @TheDukeofErl, now it's working properly! I installed at /opt.

**Comment by GiscardBiamby** [comment]
It may be a good idea to update the install instructions to have people check for nosuid first and then install under $HOME or /opt.

On ubuntu 22 I installed at the default location and then had to move the binary to /opt and update the PATH in .zshrc to reflect that.
