### ISSUE TITLE
Pipewire and Noisetorch at start

### ISSUE THREAD

**Issue by RiemaruKarurosu** [noisetorch/NoiseTorch#342]
**Describe the bug**
When I was in PulseAudio, this used to work, now in Pipewire, it shows me like if there weren't devices, then I closed and reopen and now it shows the devices 

**To Reproduce**
- Change Manjaro PulseAudio to Pipewire
- Add noisetorch as an init program

**Desktop :**
 - Distribution [e.g. Ubuntu 22.04, Arch]: Manjaro
 - DE [e.g. Plasma 5.24.5, GNOME 42.0]: Plasma
 - Pulseaudio/Pipewire Version: 1:0.3.52-1
 - NoiseTorch Version : v.0.12.2

**Screenshots**

![Screenshot_20220621_161916](https://user-images.githubusercontent.com/45057400/174899163-0108779e-3fe7-415d-8765-82868a3a667f.png)
![Screenshot_20220621_162153](https://user-images.githubusercontent.com/45057400/174899453-1016ed99-b5b7-49fe-b6c6-e3230cf622ec.png)

**Comment by TheDukeofErl** [comment]
Does this happen consistently on reboots or was this a one-off right after updating?

> Add noisetorch as an init program

I wonder if for some reason something in the pipewire stack isn't up before NoiseTorch gets started.

**Comment by binarynoise** [comment]
I have noisetorch in my autostart (with 3s delay after login) too, but I don't start the gui but run this command:
```shell
noisetorch -i -t 95
```
Does this work? Then it's a gui bug.

**Comment by ZyanKLee** [comment]
I did not encounter this issue with pipewire yet. Though I noticed, that pipewire takes a little longer to fully initiate when I login to Plasma/KDE. It just takes a second or two to finally show all the audio interfaces (in/out) and I only start noisetorch after that.

If that is the root of your problem, then the suggestion of @binarynoise may work for you, too.

**Comment by RiemaruKarurosu** [comment]
> Does this happen consistently on reboots or was this a one-off right after updating?
> 
> > Add noisetorch as an init program
> 
> I wonder if for some reason something in the pipewire stack isn't up before NoiseTorch gets started.

On every reboot or start.

**Comment by binarynoise** [comment]
> How did you manage to start it that way?

I use cinnamon, where I have an entry in my settings where I can manage my startup programmes.
There I set the delay to 3 seconds.

This setting adds an entry to the `.desktop` file in `~/.config/autostart/`:
```
X-GNOME-Autostart-Delay=3
```
So this will probably only work on gnome.

**Comment by RiemaruKarurosu** [comment]
> > So this will probably only work on gnome.
> 
> I would guess that a simple bash script could do something similar and be DE agnostic, ex
> 
> ```
> #!/bin/bash
> 
> sleep 3
> noisetorch
> ```
> 
> Even if you don't need it in gnome it could be useful for troubleshooting this in KDE-land. Just save the script named something like delayed_noisetorch.sh, chmod +x it, and add that as the autostart application instead.

Well, this worked perfectly, thank you.

**Comment by TheDukeofErl** [comment]
Going to go ahead and close this one as completed.
