### ISSUE TITLE
Update mechanism can't be disabled

### ISSUE THREAD

**Issue by legendofmiracles** [noisetorch/NoiseTorch#345]
**Describe the bug**
The update mechanism can't be disabled. This would really help us over at https://github.com/NixOS/nixpkgs/pull/179088. And all other package managers too.

**To Reproduce**
1. set updateURL to 0 and the application still tries to update

**Expected behavior**
There should be a way to disable all updates. 

**Additional context**
It also seems like the updateURL is hardcoded in https://github.com/noisetorch/NoiseTorch/blob/0f1765c1e8bd5164fe895ae4aa13e3385740d0c0/update.go#L162

**Comment by AXDOOMER** [comment]
There seems to be a way to disable it using the config file. Doesn't that work?

https://github.com/noisetorch/NoiseTorch/blob/0f1765c1e8bd5164fe895ae4aa13e3385740d0c0/main.go#L69

**Comment by TheDukeofErl** [comment]
> There seems to be a way to disable it using the config file. Doesn't that work?

If I recall correctly, previously, having UPDATE_URL unset in the makefile would result in the update mechanism being disabled at build time. While using a config file should work, it makes it harder for package distributors to have things nicely set up for distribution, as there isn't a common location (ex. some path in /etc) for configuration that can always be written to or read from.
