### ISSUE TITLE
tar -C $HOME -h -xzf NoiseTorch_x64_v0.12.2.tgz tar: Option -L is not permitted in mode -x

### ISSUE THREAD

**Issue by ivrschool** [noisetorch/NoiseTorch#353]
tar -C $HOME -h -xzf NoiseTorch_x64_v0.12.2.tgz
tar: Option -L is not permitted in mode -x

**Comment by TheDukeofErl** [comment]
Can you please provide the following?
 - Distribution [e.g. Ubuntu 22.04, Arch]: 
 - DE [e.g. Plasma 5.24.5, GNOME 42.0]:

**Comment by ZyanKLee** [comment]
I'd guess there is either an alias on `tar` or this is some form of alternative tar command like in busybox for example.
But as the OP apparently has lost interest in this question, I'll close it. Feel free to reopen if the issue still exists and none of my guesses hints at a solution.
