### ISSUE TITLE
Message NoiseTorch unconfigured

### ISSUE THREAD

**Issue by Keirodev** [noisetorch/NoiseTorch#354]
Hi,

Since monday, when I click on "Load NoiseTorch" it shows "NoiseTorch unconfigured".

I didn't find in doc / wiki anything about this message.

Do you have any idea ?

Ubuntu22.04

![image](https://user-images.githubusercontent.com/9025376/181453825-4ff8779a-1e0e-49ab-985a-2b7122b792e7.png)

**Comment by Xunjin** [comment]
When you just select filter Microphone, this happen:

![image](https://user-images.githubusercontent.com/31026338/181497821-8f02c2c4-edf0-4e03-a858-339de8b83166.png)

However, also selecting a headphone, shows that is active

![image](https://user-images.githubusercontent.com/31026338/181497942-b21b6983-ba09-43d6-93ec-8eaf98d8cd46.png)

**Comment by Keirodev** [comment]
Thanks for this solution and advice/reference to other issue.
