### ISSUE TITLE
Fedora 36 NoiseTorch makes Mic unusable

### ISSUE THREAD

**Issue by TimestaticYT** [noisetorch/NoiseTorch#363]
After trying out noise cancellation on my Dell XPS 15 9570 I tried running it and it worked shortly and I tested out the audio in discord and once I disabled it my microphone only gives off huge amounts of Noise even after I uninstalled NoiseTorch and rebooted my system. How do I fix this?

**Comment by TheDukeofErl** [comment]
I'm not really sure what's going on here, could you please include the information requested in the bug form? Specifically, in this case,
- DE [e.g. Plasma 5.24.5, GNOME 42.0]:
- Pulseaudio/Pipewire Version:
- NoiseTorch-ng Version [e.g. v0.12.0]:

`pactl list short`'s output may also be useful.
