### ISSUE TITLE
audio breaks on game launch 

### ISSUE THREAD

**Issue by Agreeable-f** [noisetorch/NoiseTorch#364]
**Describe the bug**

**To Reproduce**
1. Go to 'steam'
2. Open any game that could use your microphone. (afaik it happens when the game uses the mic that's being filtered, although could just be any mic)
3. audio (tested in discord) breaks
4. reload noisetorch. audio works but isn't filtered/no noise suppression

**Expected behavior**
noise torch continues filtering and doesn't stop working entirely.

**Screenshots**

**Logs**
If applicable, add the link to a pastebin with the output of `noisetorch -log` and `pactl list short`.

**Desktop (please complete the following information):**
 - Distribution [e.g. Ubuntu 22.04, Arch]: Garuda Linux 
 - DE [e.g. Plasma 5.24.5, GNOME 42.0]: KDE Plasma 5.25.5
 - Pipewire Version: 0.3.58
 - NoiseTorch-ng Version [e.g. v0.12.0]: 0.12.2-1 (chaotic-aur)

**Additional context**
could be pipewire breaking and causing no mic audio in general but noisetorch stops filtering noise so i'm not sure. also not sure if it's a proton issue as i've only tested it on games that use proton. haven't found a native game with voice chat.

**Comment by TheDukeofErl** [comment]
I don't believe I've had this happen before. Can you give some specific examples of games that have this issue?

**Comment by RiemaruKarurosu** [comment]
> I don't believe I've had this happen before. Can you give some specific examples of games that have this issue?

I've this issue before, but only with heavy duty games, usually when my PC doesn't accomplish the minimun requirements.

**Comment by Agreeable-f** [comment]
> I don't believe I've had this happen before. Can you give some specific examples of games that have this issue?

**Comment by Agreeable-f** [comment]
whoops. Apex legends, phasmophobia that i've tested. both have in game voice chat. sometimes when changing my mic in game it will fix. other times i'd have to reload noisetorch once, filtering breaks, then load again and hope it works again.

**Comment by Agreeable-f** [comment]
pipewire update seemes to have fixed this issue.

**Comment by TheDukeofErl** [comment]
Glad to hear that it's working better after a Pipewire update! For what it's worth, if this does happen again, it would be worthwhile to check CPU load using a tool like htop, as well as the niceness of the processes. As @RiemaruKarurosu said, things can get iffy when the system gets bogged down. NT is CPU-bound, and while this usually isn't a problem with pipewire (pulseaudio is a different story) it's still possible.

**Comment by Agreeable-f** [comment]
cpu load for noisetorch was never high, nor was it maxed out playing games (although i do have a decent cpu, i9 9900k) so that shouldn't be an issue on my system. not sure what niceness of the processes is.

**Comment by Agreeable-f** [comment]
> Glad to hear that it's working better after a Pipewire update! For what it's worth, if this does happen again, it would be worthwhile to check CPU load using a tool like htop, as well as the niceness of the processes. As @RiemaruKarurosu said, things can get iffy when the system gets bogged down. NT is CPU-bound, and while this usually isn't a problem with pipewire (pulseaudio is a different story) it's still possible.

cpu load for noisetorch was never high, nor was it maxed out playing games (although i do have a decent cpu, i9 9900k) so that shouldn't be an issue on my system. not sure what niceness of the processes is.
