### ISSUE TITLE
Document noise suppression method and differences compared to similar tools

### ISSUE THREAD

**Issue by e00E** [noisetorch/NoiseTorch#369]
I am typical linux user interested in getting noise suppression for my microphone. I found at least two maintained and popular projects that provide this:
1. NoiseTorch (this project)
2. [noise-suppression-for-voice](https://github.com/werman/noise-suppression-for-voice)

Naturally, I am wondering what the differences are so I can decide which one to use. 2's Readme tells me that they use RNNoise and that it works with PipeWire.

From looking at the source code I believe this project also uses RNNoise but I am not sure. This project lists 2 as an inspiration so it must be doing something better. What is it? These things should be part of the Readme.

**Comment by TheDukeofErl** [comment]
The biggest difference between this and noise-suppression-for-voice is that this is a simpler program that's GUI oriented. It's easier for a user to set up and doesn't require much knowledge of the terminal.

Perhaps a decent solution to this would be to add an "FAQ" section and move Latency section into it as well as adding a very short blurb of this v that and easyeffects. I would also be concerned that this section could become out of date without somebody keeping tabs on it. That said, at the end of the day I'd like to avoid a horribly long README, so should be done with with brevity.
