### ISSUE TITLE
.desktop file 'Exec=' won't run without absolute path

### ISSUE THREAD

**Issue by kjkent** [noisetorch/NoiseTorch#371]
**Describe the bug**
At least on my machine (Fedora Workstation 36 x64, KDE, using rofi in drun mode), the desktop file fails to open without an absolute path in the desktop file. Currently, the untarred file contains just `noisetorch`.

The error thrown is: `Error: 'Failed to execute child process "noisetorch" (No such file or directory)'`

**To Reproduce**
1. Untar noisetorch
2. Use rofi in drun mode to open noisetorch

**Expected behavior**
noisetorch opens

**Additional context**
I thought about the possibility of an install.sh that downloads the latest release, unpacks, and using `sed`, replaces the `Exec=` line in the .desktop file. If this or something similar is of interest, I'd be happy to implement it and open a PR.

**Comment by TheDukeofErl** [comment]
I'm not at all familiar with rofi or it's modes of running. Right off the bat I've got some questions:

- Does rofi in drun mode require absolute paths for all desktop files?
- Have you rebooted or logged in/out?
- Have you tried directly running NT from the terminal? (both with just `noisetorch` and with `~/.local/bin/noisetorch`)
- Is ~/.local/bin in your path?
- Have you tried manually setting the capabilities manually on the binary?

I think it's likely that ~/.local/bin isn't in your path if you're getting that error. You can check the path with `printenv | grep PATH`. Depending on what shell you use, the steps to adding that to your path may vary. There are instructions for bash included in [the readme](https://github.com/noisetorch/NoiseTorch#download--install).

Looking forward, the last one may also be the source of a problem once the binary runs. A very cursory glance at some of the [rofi documentation](https://mxlinux.org/wiki/help-files/help-rofi/) seems to indicate drun can't be used with anything that requires root access. The NT binary needs root access to try to set capabilities on itself. You can do this yourself: `sudo setcap 'CAP_SYS_RESOURCE=+ep' ~/.local/bin/noisetorch`.

**Comment by kjkent** [comment]
- noisetorch does run from terminal successfully with absolute, and relative paths, and by command
- ~/.local/.bin is in my PATH
- I've used the `setcap` command as per the install instructions
- Rebooting doesn't solve the issue, it's something I've noticed with noisetorch for months but only just fixed on my machine

That is a point about rofi, as I've experienced this behaviour before, but only with noisetorch, I have assumed it to be a noisetorch issue. I'll look into whether this is a rofi problem.


Kris



Kristopher James Kent
GPG Key: 97D2BF696D8C5820F31256D45C6FB9B16842920A<https://keys.openpgp.org/vks/v1/by-fingerprint/97D2BF696D8C5820F31256D45C6FB9B16842920A>



________________________________

**Comment by ZyanKLee** [comment]
We can keep this open for some time, so anyone else stumbling upon the same issue will have a chance to find the thread at rofi.
