### ISSUE TITLE
"Couldn't fetch latest release" when starting noisetorch from the terminal

### ISSUE THREAD

**Issue by dnezam** [noisetorch/NoiseTorch#374]
Hello,

when starting NoiseTorch from the terminal, I noticed the following message:
`2022/11/19 17:50:09 Couldn't fetch latest release Get "https://api.github.com/repos/noisetorch/NoiseTorch/releases/latest": dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:50108->[::1]:53: read: connection refused`

Note that this happens every time I start it from the terminal. Is this behavior normal/harmless/expected? To me this sounds like it could potentially be(come) an issue in regards to updates. I am running a fresh Arch Linux install.

EDIT: I just tried to access https://api.github.com/repos/noisetorch/NoiseTorch/releases/latest directly in Firefox, which returns a reasonable looking JSON.

Have nice day!

**Comment by ZyanKLee** [comment]
That looks a lot like an issue with your DNS resolution which is running traditionally on UDP port 53.

**Comment by jkhsjdhjs** [comment]
Just had the same issue. Now I know why starting noisetorch has become much slower since some update. But why does noisetorch check for updates anyways?

**Comment by ZyanKLee** [comment]
We do not provide any packages where users could rely on updates being done through their distro's package management. So we implemented an update system that does the grunt work for you: checking if an update is available and if so, you can easily get it with the push of a button.

**Comment by ZyanKLee** [comment]
Anyway: did fixing your dns resolver also fix noisetorch?

**Comment by ZyanKLee** [comment]
Thanks for the feedback!
