### ISSUE TITLE
could not hear when speaking in voice calls on Disocrd

### ISSUE THREAD

**Issue by bisayangdako-sec** [noisetorch/NoiseTorch#375]
It works fine for a week but when starting noisetorch today and joining voice calls on discord I could not hear myself speaking or the callers speaking. I checked my pavcontrol everything seems fine, the volume bar of noisetorch move only when I speak but I could not hear myself. I don't know much about debugging Linux audio. Here is my output.

noisetorch -l
Sources:
	Device Name: Monitor of Built-in Audio Analog Stereo
	Device ID: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor

	Device Name: Built-in Audio Analog Stereo
	Device ID: alsa_input.pci-0000_00_1b.0.analog-stereo

Sinks:
	Device Name: Built-in Audio Analog Stereo
	Device ID: alsa_output.pci-0000_00_1b.0.analog-stereo

uname -a
Linux john-yasser 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

noisetorch --log
2022/11/28 10:47:34 Application starting. Version: v0.12.2 (official)
2022/11/28 10:47:34 CAP_SYS_RESOURCE: true
2022/11/28 10:47:34 Checking if config needs to be initialized
2022/11/28 10:47:34 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/john/.config'
2022/11/28 10:47:34 Wrote temp librnnoise to: /tmp/librnnoise-1061951570.so
2022/11/28 10:47:34 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/john/.config'
2022/11/28 10:47:34 Audioserver package name: pulseaudio
2022/11/28 10:47:34 Audioserver package version: 15.99.1
2022/11/28 10:47:34 Detected PulseAudio
2022/11/28 10:47:34 Getting caps for: /home/john/.local/bin/noisetorch
2022/11/28 10:47:34 Checking for updates
2022/11/28 10:47:34 Audioserver package name: pulseaudio
2022/11/28 10:47:34 Audioserver package version: 15.99.1
2022/11/28 10:47:34 Detected PulseAudio
2022/11/28 10:47:34 Connected to audio server. Server name 'PulseAudio'
2022/11/28 10:47:34 Output alsa_output.pci-0000_00_1b.0.analog-stereo, {Index:0 Name:alsa_output.pci-0000_00_1b.0.analog-stereo Description:Built-in Audio Analog Stereo SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:7 Cvolume:[25057 25057] Muted:false MonitorSourceIndex:0 MonitorSourceName:alsa_output.pci-0000_00_1b.0.analog-stereo.monitor Latency:36968 Driver:module-alsa-card.c Flags:183 PropList:map[alsa.card:0 alsa.card_name:HDA Intel PCH alsa.class:generic alsa.device:0 alsa.driver_name:snd_hda_intel alsa.id:Generic Analog alsa.long_card_name:HDA Intel PCH at 0xc2610000 irq 30 alsa.name:Generic Analog alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap+timer device.api:alsa device.buffering.buffer_size:352800 device.buffering.fragment_size:176400 device.bus:pci device.bus_path:pci-0000:00:1b.0 device.class:sound device.description:Built-in Audio Analog Stereo device.form_factor:internal device.icon_name:audio-card-pci device.product.id:1e20 device.product.name:7 Series/C216 Chipset Family High Definition Audio Controller device.profile.description:Analog Stereo device.profile.name:analog-stereo device.string:front:0 device.vendor.id:8086 device.vendor.name:Intel Corporation module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:1b.0/sound/card0] RequestedLatency:40000 BaseVolume:65536 SinkState:1 NVolumeSteps:65537 CardIndex:0 Ports:[{Name:analog-output-speaker Description:Speakers Pririty:10000 Available:1} {Name:analog-output-headphones Description:Headphones Pririty:9900 Available:2}] ActivePortName:analog-output-headphones Formats:[{Encoding:1 PropList:map[]}]}
2022/11/28 10:47:41 Deleted temp librnnoise: /tmp/librnnoise-1061951570.so

**Comment by ZyanKLee** [comment]
Does Discord work when you do not enable NoiseTorch?  
Why do you expect to hear yourself?  
Do others hear you?

**Comment by TheDukeofErl** [comment]
Is this issue still relevant?

**Comment by TheDukeofErl** [comment]
Closing as stale.
