### ISSUE TITLE
Is there a .deb version available for download?

### ISSUE THREAD

**Issue by meg9813** [noisetorch/NoiseTorch#377]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheDukeofErl** [comment]
There isn't a packaged version for Debian/Ubuntu or any other distro for that matter. This isn't something that I would expect to change.

That said, there may be someone providing a build you can use, if that's your preferred method. There's a PKGBUILD on the AUR (Arch) and it's also in the Fedora COPR. It's also likely those could be used as a basis for a Debian package if you wanted to make one. 

With this in mind, I'm going to close this one as a won't fix.
