### ISSUE TITLE
[Pipewire] Noise torch works when hardware is selected but not when software is selected

### ISSUE THREAD

**Issue by Arcticzomb** [noisetorch/NoiseTorch#384]
**Describe the bug**
When noisetorch is set to use my headset microphone it works perfectly fine but when using an application's virtual mic output (in my case easy effects) no voice filtering works and it is just as if I am not using noisetorch.

**To Reproduce**
1. select easy effects as the noise torch microphone (headset --> easy --> torch)
2. Reload noisetorch
3. Listen to your microphone by routing in whatever way allows you to hear it. (using helvum/qpw and routing the noisetorch monitor to your headset is a pretty easy way to do so)
4. select base headset mic in noisetorch\
5. reload noisetorch and compare

**Expected behavior**
Noisetorch mic filtering to work properly. 

**Logs**
https://pastebin.com/mCC23QvQ (first section is noisetorch log, second is pactl)

**Desktop (please complete the following information):**
 - Distribution [e.g. Ubuntu 22.04, Arch]: Manjaro/Arch
 - DE [e.g. Plasma 5.24.5, GNOME 42.0]: Plasma 5.26.5
 - Pulseaudio/Pipewire Version: Pipewire 0.3.65
 - NoiseTorch-ng Version [e.g. v0.12.0]: v0.12.2

**Additional context**
N/A

**Comment by ZyanKLee** [comment]
Thanks for reporting this issue.
As we are currently in the phase of rewriting part of the application and as the pipewire support is still in an alpha state and mostly untested, I would drop this bug to the backlog of issues we should tackle once we are done with the rewriting.

Out of sheer curiosity: why do you want to use both EasyEffects and NT? Afair EasyEffects employs the same noise-filter as NT, doesn't it?

**Comment by Arcticzomb** [comment]
It does also have noise-filtering along with a lot of effects. I was testing it and noticed that it did not work.

**Comment by TheDukeofErl** [comment]
>Should I close the thread?

I think I concur with this: EasyEffects implements more or less the same thing so I don't believe this is necessary functionality?

**Comment by Arcticzomb** [comment]
Yeah go ahead. I completely forgot about this. I moved on to another set up anyways.
