### ISSUE TITLE
Start with System (pipewire)

### ISSUE THREAD

**Issue by DSDV** [noisetorch/NoiseTorch#385]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A button which loads noise torch on starup

**Describe alternatives you've considered**
i looked ad a dead github:
[NoiseTorch](https://github.com/lawl/NoiseTorch)

**Additional context**
I don't know why https://github.com/noisetorch/NoiseTorch/issues/6 is closed. 
but i cant find a simple (i am not a developer) way to run noise torch on startup (running app on start does not seam to load noise torch itself but only starts the gui). 
The github linked in the repo with i guess held instructions for automatic loading at startup is dead. 

So pls add an option <3

with kind regards

PS: if it helps i am currently on the latest manjaro with pipewire

**Comment by njanke96** [comment]
I think I just figured this out for myself, I have my DE run this command on login:

```shell
noisetorch -s alsa_input.pci-0000_04_00.6.analog-stereo -i -o
```

Where `alsa_input.pci-0000_04_00.6.analog-stereo` is a device ID I saw listed in the output of `noisetorch -l`

Now when I log in the virtual device is listed in apps and I never had to open the GUI. Still, a possible enhancement would be to provide a systemd user service for this.

**Comment by DSDV** [comment]
Its really nice to see that there is a workaround. 
But as you said i small button in the GUI for autolload would be nice! 
Especially for folks like me who are not that qualified in console work :/

**Comment by TheDukeofErl** [comment]
For what it's worth, there are some instructions on the wiki for how to make this work: https://github.com/noisetorch/NoiseTorch/wiki/Start-automatically-with-Systemd.

**Comment by FichteFoll** [comment]
See also https://github.com/noisetorch/NoiseTorch/issues/211#issuecomment-1008769617.

**Comment by DSDV** [comment]
Moved to fedora and https://github.com/werman/noise-suppression-for-voice (:
