### ISSUE TITLE
cant start noisetorch after updating pipewire

### ISSUE THREAD

**Issue by GeorgiLudiq** [noisetorch/NoiseTorch#395]
i updated pipewire (and rebooted like 40 times already) and i cant turn on noisetorch 
output from noisetorch -log

`2023/04/06 20:44:37 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/goshko812/.config'
2023/04/06 20:44:37 Wrote temp librnnoise to: /tmp/librnnoise-3244813986.so
2023/04/06 20:44:37 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/goshko812/.config'
2023/04/06 20:44:37 Audioserver package name: PulseAudio (on PipeWire 0.3.67)
2023/04/06 20:44:37 Audioserver package version: 15.0.0
2023/04/06 20:44:37 Detected PipeWire
2023/04/06 20:44:37 Getting caps for: /usr/bin/noisetorch
2023/04/06 20:44:37 Audioserver package name: PulseAudio (on PipeWire 0.3.67)
2023/04/06 20:44:37 Audioserver package version: 15.0.0
2023/04/06 20:44:37 Detected PipeWire
2023/04/06 20:44:37 Connected to audio server. Server name 'PipeWire'
2023/04/06 20:44:37 Output alsa_output.pci-0000_00_1f.3.analog-stereo, {Index:41 Name:alsa_output.pci-0000_00_1f.3.analog-stereo Description:Built-in Audio Analog Stereo SampleSpec:{Format:7 Channels:2 Rate:48000} ChannelMap:[1 2] ModuleIndex:4294967295 Cvolume:[65536 65536] Muted:false MonitorSourceIndex:41 MonitorSourceName:alsa_output.pci-0000_00_1f.3.analog-stereo.monitor Latency:0 Driver:PipeWire Flags:183 PropList:map[alsa.card:0 alsa.card_name:HDA Intel PCH alsa.class:generic alsa.device:0 alsa.driver_name:snd_hda_intel alsa.id:ALC887-VD Analog alsa.long_card_name:HDA Intel PCH at 0xf7220000 irq 128 alsa.name:ALC887-VD Analog alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 api.acp.auto-port:false api.acp.auto-profile:false api.alsa.card:0 api.alsa.card.longname:HDA Intel PCH at 0xf7220000 irq 128 api.alsa.card.name:HDA Intel PCH
api.alsa.path:front:0 api.alsa.pcm.card:0 api.alsa.pcm.stream:playback api.alsa.use-acp:true api.dbus.ReserveDevice1:Audio0 audio.adapt.follower: audio.channels:2 audio.position:FL,FR card.profile.device:4 client.id:33 clock.quantum-limit:8192 device.api:alsa device.bus:pci device.bus_path:pci-0000:00:1f.3 device.class:sound device.description:Built-in Audio device.enum.api:udev device.form_factor:internal device.icon_name:audio-card-analog-pci device.id:40 device.name:alsa_card.pci-0000_00_1f.3 device.nick:HDA Intel PCH device.plugged.usec:24022952 device.product.id:0xa2f0 device.product.name:200 Series PCH HD Audio device.profile.description:Analog Stereo device.profile.name:analog-stereo
device.routes:2 device.string:0 device.subsystem:sound device.vendor.id:0x8086 device.vendor.name:Intel Corporation factory.id:18 factory.mode:merge factory.name:api.alsa.pcm.sink library.name:audioconvert/libspa-audioconvert media.class:Audio/Sink node.driver:true node.name:alsa_output.pci-0000_00_1f.3.analog-stereo node.nick:ALC887-VD Analog node.pause-on-idle:false object.id:41 object.path:alsa:pcm:0:front:0:playback object.serial:41 priority.driver:1009 priority.session:1009 sysfs.path:/devices/pci0000:00/0000:00:1f.3/sound/card0] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:0 CardIndex:40 Ports:[{Name:analog-output-lineout Description:Line Out Pririty:9000 Available:1} {Name:analog-output-headphones Description:Headphones Pririty:9900 Available:2}] ActivePortName:analog-output-headphones Formats:[{Encoding:1 PropList:map[]}]}
2023/04/06 20:44:44 Loading supressor for pipewire
2023/04/06 20:44:44 Error loading input: PulseAudio error: commandLoadModule -> No such entity
2023/04/06 20:44:44 PulseAudio error: commandLoadModule -> No such entity
2023/04/06 20:44:55 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/goshko812/.config'
`

**Comment by TheDukeofErl** [comment]
Can you please include the rest of the required information on the bug report issue submission list?

```
**Logs**
If applicable, add the link to a pastebin with the output of `noisetorch -log` and `pactl list short`.

**Desktop (please complete the following information):**
 - Distribution [e.g. Ubuntu 22.04, Arch]: 
 - DE [e.g. Plasma 5.24.5, GNOME 42.0]: 
 - Pulseaudio/Pipewire Version: 
 - NoiseTorch-ng Version [e.g. v0.12.0]:
```

It's also worth noting that codeblocks or logs dumped on github should be wrapped with three `, not just one, in the case that they're more than one line long. It helps a lot with readability, as it avoids the "one long line of wrapping text" issue.

Could you please also verify  that XDG_CONFIG_HOME is set? Some parts of XDG_CONFIG_HOME vary from distro to distro, making the bug report information essential.

**Comment by TheDukeofErl** [comment]
Please also include the output of `pactl list short`.

**Comment by GeorgiLudiq** [comment]
```goshko812 in ~ λ pactl list short
1       libpipewire-module-rt   {
            nice.level    = -11
            #rt.prio      = 88
            #rt.time.soft = -1
            #rt.time.hard = -1
        }
2       libpipewire-module-protocol-native
3       libpipewire-module-profiler
5       libpipewire-module-metadata
7       libpipewire-module-spa-device-factory
9       libpipewire-module-spa-node-factory
11      libpipewire-module-client-node
13      libpipewire-module-client-device
15      libpipewire-module-portal
16      libpipewire-module-access       {
            # access.allowed to list an array of paths of allowed
            # apps.
            #access.allowed = [
            #    /usr/bin/pipewire-media-session
            #]

            # An array of rejected paths.
            #access.rejected = [ ]

            # An array of paths with restricted access.
            #access.restricted = [ ]

            # Anything not in the above lists gets assigned the
            # access.force permission.
            #access.force = flatpak
        }
17      libpipewire-module-adapter
19      libpipewire-module-link-factory
21      libpipewire-module-session-manager
536870912       module-always-sink
48      alsa_output.pci-0000_00_1f.3.analog-stereo      PipeWire        s32le 2ch 48000Hz       IDLE
48      alsa_output.pci-0000_00_1f.3.analog-stereo.monitor      PipeWire        s32le 2ch 48000Hz       RUNNING
49      alsa_input.pci-0000_00_1f.3.analog-stereo       PipeWire        s32le 2ch 48000Hz       RUNNING
58      48      57      PipeWire        float32le 1ch 25Hz
59      49      57      PipeWire        float32le 1ch 25Hz
31      PipeWire        pipewire
32      PipeWire        polybar
34      PipeWire        wireplumber
35      PipeWire        wireplumber
41      PipeWire        volumeicon
56      PipeWire        xdg-desktop-portal
57      PipeWire        pavucontrol
76      PipeWire        pactl
42      alsa_card.pci-0000_01_00.1      alsa
43      alsa_card.pci-0000_00_1f.3      alsa
```

**Comment by GeorgiLudiq** [comment]
this may be helpful too from the `journalctl -xe | grep pipewire`

```апр 07 02:17:42 goshko812-arch pipewire[775]: mod.rt: Can't find org.freedesktop.portal.Desktop. Is xdg-desktop-portal running?
апр 07 02:17:42 goshko812-arch pipewire[775]: mod.rt: found session bus but no portal
апр 07 02:17:42 goshko812-arch pipewire-pulse[777]: mod.rt: Can't find org.freedesktop.portal.Desktop. Is xdg-desktop-portal running?
апр 07 02:17:42 goshko812-arch pipewire-pulse[777]: mod.rt: found session bus but no portal
апр 07 02:17:42 goshko812-arch dbus-daemon[475]: [system] Activating via systemd: service name='org.freedesktop.RealtimeKit1' unit='rtkit-daemon.service' requested by ':1.21' (uid=1000 pid=775 comm="/usr/bin/pipewire")
апр 07 02:19:33 goshko812-arch pipewire-pulse[777]: mod.protocol-pulse: 0x563473720e90: [noisetorch] failed to load module index:536870913 name:module-ladspa-source tag:1 result:-2 (No such file or directory)```

**Comment by TheDukeofErl** [comment]
Aha, I think I see something that could cause an issue.

> `alsa_input.pci-0000_00_1f.3.analog-stereo       PipeWire        s32le 2ch 48000Hz`

If I recall correctly, the device used for noise cancellation has to be 16bit/48kHz. I believe that's what pipewire always defaults to as well. I'm going to go out on a limb and guess that you've manually set that in your pipewire configuration. Could you please try removing that or setting it to `s16le 2ch 48000Hz`?

**Comment by GeorgiLudiq** [comment]
i use the default config i dont think thats the problem could it be something with pipewire-pulse because
```PulseAudio error: commandLoadModule -> No such entity 2023/04/06 20:44:55
goshko812-arch pipewire-pulse[777]: mod.protocol-pulse: 0x563473720e90: [noisetorch] failed to load module index:536870913 name:module-ladspa-source tag:1 result:-2 (No such file or directory```

**Comment by GeorgiLudiq** [comment]
and 
```PulseAudio error: commandLoadModule -> No such entity 2023/04/06 20:44:55```

**Comment by GeorgiLudiq** [comment]
i just deleted pipewire entirely i wiped all the configs and i reinstalled it and it started working again
