### ISSUE TITLE
Is it possible to extract the RNN model from noisetorch and use it other places?

### ISSUE THREAD

**Issue by the-eclectic-dyslexic** [noisetorch/NoiseTorch#404]
**Is your feature request related to a problem? Please describe.**
I currently use NoiseTorch (in pipewire) in conjunction with easy effects because I find easy effects' is not nearly as good at noise reduction as NoiseTorch... despite them both using RNN. The problem with this is trying to juggle the virtual microphones can be a little finicky... and it gets even worse when trying to juggle virtual outputs. Often, I have to resort to manually editing the wireplumber connections to get them to play nice together the way I would like.

**Describe the solution you'd like**
Is there a way that I could extract the RNN model from noisetorch and import it into easy effects? Easy effects seems to have a method for importing RNN models, but I am having difficulty figuring out where the RNN model in NoiseTorch is... Would importing it even keep the full capabilities of NoiseTorch? Is noise torch even using a different model to easy effects?... or is all the difference found in settings used by NoiseTorch on top of the same standard model easy effects uses? In conclusion, I am trying to sort of the opposite of #175 

**Describe alternatives you've considered**
I have tried running them both, feeding one virtual microphone into another, and this works okay... most of the time. Ocassionally, noise torch will ignore the input I try to have it use via the -i option, and instead of grabbing my physical microphone it grabs the easy effects virtual microphone... creating the pipewire equivalent of an eternally silent oroboros haha.

Probably the absolute best solution (which is also likely by far the most work) I see was already proposed a while back with #237 Honestly... it would be really handy if noisetorch had the ability to act as a VST plugin. It would open up a few options, including being able to be used in programs like ardour. (I am almost tempted to take a crack at it myself)

**Additional context**
N/A

**Comment by ZyanKLee** [comment]
the RNN model is not build by noisetorch and is actually taken from https://github.com/xiph/rnnoise
So, yes.

**Comment by the-eclectic-dyslexic** [comment]
Okay, great. So there isn't really anything, on the front of rnnoise, noisetorch is doing to stray from the default. 

The reason I ask is, as far as I can tell, the easy effects "Noise Reduction" plugin is using the same model. Yet, they act VERY differently. For instance, lip puckering, mouse clicks, and creaking chair sounds get very reliably removed by noisetorch, but never seem to be removed by the easy effects plugin, despite them in theory using the same default rnnoise model. 

Thanks very much for your help. I am going to investigate this further, from the easy effects side, because it seems really really odd to me that these two tools would act so differently... when it seems the only special things noise torch are doing are down-mixing to mono and applying a voice activation threshold.

Any additional insight you could give would be really appreciated, because I would love to get these two tools working together better than they currently do.

**Comment by TheDukeofErl** [comment]
> when it seems the only special things noise torch are doing are down-mixing to mono and applying a voice activation threshold.
>
> Any additional insight you could give would be really appreciated, because I would love to get these two tools working together better than they currently do.

As you've already noticed, NT uses a threshold. Here's a little bit of info on that threshold and where to look to get a better understanding.

The file you're gonna wanna look at is https://github.com/noisetorch/NoiseTorch/blob/master/c/ladspa/module.c. Of particular interest here are going to be `VAD_GRACE_PERIOD` and `vad_thresh`. I have no idea if EasyEffects is doing things similarly, but if it is, you may need to determine what a good threshold is.

Additionally, for EasyEffects, I'd put some thought into how you build your filter chain. It may make the most sense to do something as follows: `source -> rnnoise -> noise gate -> output`. That said, I'm no EasyEffects expert. It may be worth asking over there as well.

Just some food for though.

**Comment by TheDukeofErl** [comment]
For what it's worth, it seems like EasyEffects has updated their RNN plugin to also include a gate similar to what noisetorch is doing. I'm going to go ahead and close this one, as I don't think there's much for us to do here, and with EasyEffects now being updated to act this way the original request is (kind of) fullfilled(ish).
