### ISSUE TITLE
 `Failed to execute command "noisetorch"` on XFCE DE

### ISSUE THREAD

**Issue by GinoongFlores** [noisetorch/NoiseTorch#432]
**Describe the bug**
Cannot run the software through the icon. Yet, I can run through the command line using `~/.local/bin/noisetorch`. Although I found the same issue on this https://github.com/noisetorch/NoiseTorch/issues/371. Still, I can't figure out the solution as I'm quite a newbie in Linux. 

**To Reproduce**
I search noisetorch through my XFCE DE and the error says `Failed to execute command "noisetorch"` `Failed to execute child process "noisetorch" (No such file or directory)`

**Expected behavior**
The program should run after clicking it's icon

**Screenshots**
<img title="a title" alt="Alt text" src="https://i.imgur.com/y5va1Cx.png">

**Logs**
`Failed to execute command "noisetorch"` 
`Failed to execute child process "noisetorch" (No such file or directory)`

**Desktop (please complete the following information):**
 - Distribution [e.g. Ubuntu 22.04, Arch]: MX 86_64 23.1
 - DE [e.g. Plasma 5.24.5, GNOME 42.0]: XFCE 4.18
 - Pulseaudio/Pipewire Version: Pulseaudio 16.1
 - NoiseTorch-ng Version [e.g. v0.12.0]: v0.12.2

**Additional context**
I already followed all the necessary steps on the instructions and tried to reinstall noisetorch and pulseaudio.

**Comment by LostWarriorr** [comment]
Add this to ~/.xsessionrc and logout/login

`
case "$PATH" in
   *$HOME/.local/bin*) ;;
   *) PATH=$HOME/.local/bin/:"$PATH"
esac
export PATH

`

**Comment by GinoongFlores** [comment]
> Add this to ~/.xsessionrc and logout/login
> 
> `case "$PATH" in`
> `   *$HOME/.local/bin*) ;;`
> `   *) PATH=$HOME/.local/bin/:"$PATH"`
> `esac`
> `export PATH`
> 
> 
> Edit: I suck at formatting

Thanks! Fortunately, I switched now to Fedora and there's not quite an issue.

**Comment by LostWarriorr** [comment]
I only recently switched to xfce and yeah it is a bit dated and missing a lot of convenient features, tweaks, and QoL stuff. I probably won't be on it much longer due to some issues I am having with it compared to some newer DEs.

**Comment by GinoongFlores** [comment]
> I only recently switched to xfce and yeah it is a bit dated and missing a lot of convenient features, tweaks, and QoL stuff. I probably won't be on it much longer due to some issues I am having with it compared to some newer DEs.

XFCE is snappy and good for low-end machines. I forgot to mention that my DE is XFCE on Fedora. Somewhat it's not the DE but the distro.
