### ISSUE TITLE
Allow overriding mic boost setting

### ISSUE THREAD

**Issue by tilda** [noisetorch/NoiseTorch#447]
**Is your feature request related to a problem? Please describe.**
My ThinkPad T470 has *very* bad mic quality whenever its volume is boosted. NoiseTorch(?) forcibly enables full boost on it and as a result, it sounds horrible until I go into alsamixer manually and fix it.

**Describe the solution you'd like**
Some checkbox for leaving the volume config on the source mic alone.

**Describe alternatives you've considered**
Changing "Internal Mic Boost" to 0 every time I need to use NoiseTorch is not a great solution, even if it works.

**Additional context**
I'm on PipeWire 1.0.7.

**Comment by tilda** [comment]
Actually I don't know if it's Discord doing this or NoiseTorch but I'll need to do some research

**Comment by tilda** [comment]
Okay I definitely think it's Discord, never mind. Sorry

**Comment by lemon4sour** [comment]
My apologies for reviving a completed issue, but have you found a way to stop Discord from doing that? Thanks.

**Comment by tilda** [comment]
@lemon4sour Sorry for the late reply; to be honest, I don't think I was able to fix it. Migrated to EasyEffects which has a similar function.
